lib/tq2_web/router.ex
defmodule Tq2Web.Router do
  use Tq2Web, :router

  @session_extras %{
    current_session: {Tq2Web.SessionPlug, :session_extras, [:current_session]},
    registration: {Tq2Web.SessionPlug, :session_extras, [:registration]},
    store: {Tq2Web.SessionPlug, :session_extras, [:store]}
  }

  pipeline :csrf do
    plug :protect_from_forgery
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :fetch_current_session
    plug :check_locked_license
    plug :put_root_layout, {Tq2Web.LayoutView, :root}
    plug :put_secure_browser_headers
    plug :put_cache_control_headers

    if Application.get_env(:tq2, :env) == :prod do
      plug Tq2Web.SSLPlug,
        host: nil,
        hsts: true,
        preload: true,
        subdomains: true,
        rewrite_on: [:x_forwarded_proto]
    end
  end

  pipeline :store do
    plug :fetch_store
    plug :fetch_token
    plug :track_visit
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :put_cache_control_headers
  end

  pipeline :pwa do
    plug :accepts, ["html", "json", "js"]
    plug :put_secure_browser_headers
    plug :put_cache_control_headers
  end

  scope "/", Tq2Web, host: Application.get_env(:tq2, :web_host) do
    pipe_through :browser

    get "/", PageController, :index
    get "/terms", LegalController, :index
    get "/:country", PageController, :index
  end

  scope "/", Tq2Web do
    pipe_through :pwa

    get "/service-worker.js", PwaController, :service_worker
    get "/manifest.json", PwaController, :manifest
    get "/offline.html", PwaController, :offline
  end

  scope "/", Tq2Web, host: "#{Application.get_env(:tq2, :store_subdomain)}." do
    pipe_through [:browser, :csrf, :store]

    put "/:slug/session/dismiss_price_info", Store.SessionController, :dismiss_price_info,
      as: :store_dismiss_price_info

    live "/:slug", Store.CounterLive, :index, session: @session_extras.store
    live "/:slug/items/:id", Store.ItemLive, :index, session: @session_extras.store
    live "/:slug/handing", Store.HandingLive, :index, session: @session_extras.store
    live "/:slug/customer", Store.CustomerLive, :index, session: @session_extras.store
    live "/:slug/payment", Store.PaymentLive, :index, session: @session_extras.store
    live "/:slug/payment/check", Store.PaymentCheckLive, :index, session: @session_extras.store
    live "/:slug/order/:id", Store.OrderLive, :index, session: @session_extras.store
    live "/:slug/team", Store.TeamLive, :index, session: @session_extras.store
    live "/:slug/checkout", Store.CheckoutLive, :index, session: @session_extras.store
    live "/:slug/brief", Store.BriefLive, :index, session: @session_extras.store

    get "/:slug/tokens/:token", TokenController, :show
    get "/:slug/cart/:from", CartController, :show
  end

  scope "/", Tq2Web, host: "#{Application.get_env(:tq2, :store_subdomain)}." do
    pipe_through [:browser, :store]

    post "/:slug/payment/transbank", Store.PaymentController, :transbank, as: :transbank_payment
  end

  scope "/", Tq2Web do
    pipe_through [:browser, :csrf]

    get "/", RootController, :index
    get "/healthy", HealthController, :index

    resources(
      "/sessions",
      SessionController,
      only: [:new, :create, :delete],
      singleton: true
    )

    # Registration
    live "/registrations/new", Registration.NewLive, :index,
      as: "registration",
      session: @session_extras.registration

    get "/registrations/:uuid", RegistrationController, :show
    live "/tour", Registration.TourLive, :index
    live "/welcome", Registration.WelcomeLive, :index

    # Accounts
    resources "/accounts", AccountController, only: [:index, :show, :update]
    resources "/users", UserController
    resources "/passwords", PasswordController, only: [:new, :create, :edit, :update]
    live "/license", Account.LicenseLive, :index

    # Apps
    resources "/apps", AppController, param: "name"

    # Dashboard
    live "/dashboard", Dashboard.MainLive, :index, as: :dashboard

    # Inventories
    resources "/categories", CategoryController
    live "/items/new", Inventory.ItemLive, :new, session: @session_extras.current_session
    live "/items/:id/edit", Inventory.ItemLive, :edit, session: @session_extras.current_session
    resources "/items", ItemController, only: [:index, :show, :delete]
    live "/import", Inventory.ImportLive, :index
    live "/import/:section", Inventory.ImportOptionsLive, :show, as: :import

    # News
    resources "/notes", NoteController

    # Shops
    live "/store/edit/:section", Shop.StoreLive, :index, session: @session_extras.current_session

    # Sales
    resources "/orders", OrderController, only: [:index, :show]
    live "/orders/:id/edit", Order.OrderEditLive, :index, session: @session_extras.current_session

    live "/orders/:id/comments", Order.CommentLive, :index,
      session: @session_extras.current_session

    live "/orders/:id/payments", Order.PaymentLive, :index,
      as: :order_payment,
      session: @session_extras.current_session

    live "/carts", Cart.IndexLive, :index, session: @session_extras.current_session, as: :cart
    live "/carts/:id", Cart.ShowLive, :show, session: @session_extras.current_session, as: :cart
  end

  # Other scopes may use custom stacks.
  scope "/api", Tq2Web do
    pipe_through :api

    post "/webhooks/mercado_pago", WebhookController, :mercado_pago
    post "/webhooks/stripe", WebhookController, :stripe
  end

  if Application.get_env(:tq2, :env) == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Application.get_env(:tq2, :env) in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/phx-dashboard", metrics: Tq2Web.Telemetry
    end
  end
end

lib/tq2_web/templates/app/_conekta.html.eex
<div class="media my-3">
  <%= app_img_tag(@conn, @app.name) %>

  <div class="media-body">
    <h2 class="h5 mt-0 mb-1 font-weight-semi-bold">
      <%= translate_app(@app.name) %>
    </h2>

    <%= if @app.id do %>
      <%= app_status @app %>

      <ul class="list-unstyled lead mt-2">
        <li class="mb-1">
          <%= link_to_edit(@conn, @app) %>
        </li>

        <li class="mb-1">
          <%= link_to_commissions(@account, @app.name) %>
        </li>
      </ul>
    <% else %>
      <%= link_to_install(@conn, @app.name) %>

      <p class="lead mt-4">
        <%= link_to_commissions(@account, @app.name) %>
      </p>
    <% end %>
  </div>
</div>

lib/tq2_web/templates/app/_form_conekta.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger rounded-pill">
      <p class="mb-0"><%= dgettext("apps", "Oops, something went wrong! Please check the errors below.") %></p>
    </div>
  <% end %>

  <%= input f, :status, dgettext("apps", "Status"), collection: statuses_collection() %>

  <%= inputs_for f, :data, fn df -> %>
    <%= input df, :api_key, dgettext("conekta", "Production API Key") %>
  <% end %>

  <%= lock_version_input(f, assigns[:app]) %>

  <div class="text-right">
    <%= submit_button assigns[:app] %>
  </div>
<% end %>

<%= render(YoutubeModal, "show.html", title: translate_app(@app_name), url: "https://www.youtube.com/embed/H7mH6Sq8y_A") %>

lib/tq2_web/templates/app/_form_mercado_pago.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger rounded-pill">
      <p class="mb-0"><%= dgettext("apps", "Oops, something went wrong! Please check the errors below.") %></p>
    </div>
  <% end %>

  <%= input f, :status, dgettext("apps", "Status"), collection: statuses_collection() %>

  <%= inputs_for f, :data, fn df -> %>
    <%= input df, :access_token, dgettext("mercado_pago", "Access Token") %>
  <% end %>

  <%= lock_version_input(f, assigns[:app]) %>

  <div class="text-right">
    <%= submit_button assigns[:app] %>
  </div>
<% end %>

<%= render(YoutubeModal, "show.html", title: translate_app(@app_name), url: "https://www.youtube.com/embed/4QdUjnb0V5A") %>

lib/tq2_web/templates/app/_form_transbank.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger rounded-pill">
      <p class="mb-0"><%= dgettext("apps", "Oops, something went wrong! Please check the errors below.") %></p>
    </div>
  <% end %>

  <%= input f, :status, dgettext("apps", "Status"), collection: statuses_collection() %>

  <%= inputs_for f, :data, fn df -> %>
    <%= input df, :api_key, dgettext("transbank", "Api key") %>
    <%= input df, :shared_secret, dgettext("transbank", "Shared secret") %>
  <% end %>

  <%= lock_version_input(f, assigns[:app]) %>

  <div class="text-right">
    <%= submit_button assigns[:app] %>
  </div>
<% end %>

lib/tq2_web/templates/app/_form_wire_transfer.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger rounded-pill">
      <p class="mb-0"><%= dgettext("apps", "Oops, something went wrong! Please check the errors below.") %></p>
    </div>
  <% end %>

  <%= input f, :status, dgettext("apps", "Status"), collection: statuses_collection() %>
  <%= inputs_for f, :data, fn df -> %>
    <%= input df, :description, dgettext("apps", "Description") %>
    <%= input df, :account_number, dgettext("apps", "Account number") %>
  <% end %>

  <%= lock_version_input f, assigns[:app] %>

  <div class="text-right">
    <%= submit_button assigns[:app] %>
  </div>
<% end %>

lib/tq2_web/templates/app/_mercado_pago.html.eex
<div class="media my-3">
  <%= app_img_tag(@conn, @app.name) %>

  <div class="media-body">
    <h2 class="h5 mt-0 mb-1 font-weight-semi-bold">
      <%= dgettext("apps", "MercadoPago") %>
    </h2>

    <%= if @app.id do %>
      <%= app_status @app %>

      <ul class="list-unstyled lead mt-2">
        <li class="mb-1">
          <%= link_to_edit(@conn, @app) %>
        </li>

        <li class="mb-1">
          <%= mp_link_to_commissions(@account) %>
        </li>
      </ul>
    <% else %>
      <%= link_to_install(@conn, @app.name) %>

      <p class="lead mt-4">
        <%= mp_link_to_commissions(@account) %>
      </p>
    <% end %>
  </div>
</div>

lib/tq2_web/templates/app/_transbank.html.eex
<div class="media my-3">
  <%= app_img_tag(@conn, @app.name) %>

  <div class="media-body">
    <h2 class="h5 mt-0 mb-1 font-weight-semi-bold">
      <%= translate_app(@app.name) %>
    </h2>

    <%= if @app.id do %>
      <%= app_status @app %>

      <ul class="list-unstyled lead mt-2">
        <li class="mb-1">
          <%= link_to_edit(@conn, @app) %>
        </li>

        <li class="mb-1">
          <%= link_to_commissions(@account, @app.name) %>
        </li>
      </ul>
    <% else %>
      <%= link_to_install(@conn, @app.name) %>

      <p class="lead mt-4">
        <%= link_to_commissions(@account, @app.name) %>
      </p>
    <% end %>
  </div>
</div>

lib/tq2_web/templates/app/_wire_transfer.html.eex
<div class="media my-3">
  <%= app_img_tag(@conn, @app.name) %>

  <div class="media-body">
    <h2 class="h5 mt-0 mb-1 font-weight-semi-bold">
      <%= dgettext("apps", "Wire transfer") %>
    </h2>

    <%= if @app.id do %>
      <%= app_status @app %>

      <ul class="list-unstyled lead mt-2">
        <li class="mb-1">
          <%= link_to_edit(@conn, @app) %>
        </li>
      </ul>
    <% else %>
      <%= link_to_install(@conn, @app.name) %>
    <% end %>
  </div>
</div>

lib/tq2_web/templates/app/edit.html.eex
<div class="card my-3">
  <div class="card-header">
    <h2 class="h5">
      <%= translate_app(@app_name) %>
    </h2>
  </div>

  <%= instructions(@account, @app_name) %>

  <div class="card-body">
    <%= render "_form_#{@app_name}.html", assigns %>
  </div>
</div>

<div class="mt-3">
  <%= link dgettext("apps", "Back"), to: Routes.app_path(@conn, :index) %> |
  <%= link_to_delete(@conn, @app) %>
</div>

lib/tq2_web/templates/app/edit_wire_transfer.html.eex
<div class="card my-3">
  <div class="card-header">
    <h2 class="h5">
      <%= dgettext("apps", "Wire transfer") %>
    </h2>
  </div>

  <div class="card-body">
    <%= render "_form_wire_transfer.html", assigns %>
  </div>
</div>

<div class="mt-3">
  <%= link dgettext("apps", "Back"), to: Routes.app_path(@conn, :index) %> |
  <%= link_to_delete(@conn, @app) %>
</div>

lib/tq2_web/templates/app/index.html.eex
<h1 class="h3">
  <%= dgettext("apps", "Apps") %>
</h1>

<%= for app_name <- app_names(@account) do %>
  <%= render "_#{app_name}.html", Map.put(assigns, :app, app_by_name(@apps, app_name)) %>
<% end %>

lib/tq2_web/templates/app/new.html.eex
<div class="card my-3">
  <div class="card-header">
    <h2 class="h5">
      <%= translate_app(@app_name) %>
    </h2>
  </div>

  <%= instructions(@account, @app_name) %>

  <div class="card-body">
    <%= render "_form_#{@app_name}.html", assigns %>
  </div>
</div>

<div class="mt-3">
  <%= link dgettext("apps", "Back"), to: Routes.app_path(@conn, :index) %>
</div>

lib/tq2_web/templates/app/new_wire_transfer.html.eex
<div class="card my-3">
  <div class="card-header">
    <h2 class="h5">
      <%= dgettext("apps", "Wire transfer") %>
    </h2>
  </div>

  <div class="card-body">
    <%= render "_form_wire_transfer.html", assigns %>
  </div>
</div>

<div class="mt-3">
  <%= link dgettext("apps", "Back"), to: Routes.app_path(@conn, :index) %>
</div>