lib/tq2_web/router.ex
defmodule Tq2Web.Router do
  use Tq2Web, :router

  @session_extras %{
    current_session: {Tq2Web.SessionPlug, :session_extras, [:current_session]},
    registration: {Tq2Web.SessionPlug, :session_extras, [:registration]},
    store: {Tq2Web.SessionPlug, :session_extras, [:store]}
  }

  pipeline :csrf do
    plug :protect_from_forgery
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :fetch_current_session
    plug :check_locked_license
    plug :put_root_layout, {Tq2Web.LayoutView, :root}
    plug :put_secure_browser_headers
    plug :put_cache_control_headers

    if Application.get_env(:tq2, :env) == :prod do
      plug Tq2Web.SSLPlug,
        host: nil,
        hsts: true,
        preload: true,
        subdomains: true,
        rewrite_on: [:x_forwarded_proto]
    end
  end

  pipeline :store do
    plug :fetch_store
    plug :fetch_token
    plug :track_visit
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :put_cache_control_headers
  end

  pipeline :pwa do
    plug :accepts, ["html", "json", "js"]
    plug :put_secure_browser_headers
    plug :put_cache_control_headers
  end

  scope "/", Tq2Web, host: Application.get_env(:tq2, :web_host) do
    pipe_through :browser

    get "/", PageController, :index
    get "/terms", LegalController, :index
    get "/:country", PageController, :index
  end

  scope "/", Tq2Web do
    pipe_through :pwa

    get "/service-worker.js", PwaController, :service_worker
    get "/manifest.json", PwaController, :manifest
    get "/offline.html", PwaController, :offline
  end

  scope "/", Tq2Web, host: "#{Application.get_env(:tq2, :store_subdomain)}." do
    pipe_through [:browser, :csrf, :store]

    put "/:slug/session/dismiss_price_info", Store.SessionController, :dismiss_price_info,
      as: :store_dismiss_price_info

    live "/:slug", Store.CounterLive, :index, session: @session_extras.store
    live "/:slug/items/:id", Store.ItemLive, :index, session: @session_extras.store
    live "/:slug/handing", Store.HandingLive, :index, session: @session_extras.store
    live "/:slug/customer", Store.CustomerLive, :index, session: @session_extras.store
    live "/:slug/payment", Store.PaymentLive, :index, session: @session_extras.store
    live "/:slug/payment/check", Store.PaymentCheckLive, :index, session: @session_extras.store
    live "/:slug/order/:id", Store.OrderLive, :index, session: @session_extras.store
    live "/:slug/team", Store.TeamLive, :index, session: @session_extras.store
    live "/:slug/checkout", Store.CheckoutLive, :index, session: @session_extras.store
    live "/:slug/brief", Store.BriefLive, :index, session: @session_extras.store

    get "/:slug/tokens/:token", TokenController, :show
    get "/:slug/cart/:from", CartController, :show
  end

  scope "/", Tq2Web, host: "#{Application.get_env(:tq2, :store_subdomain)}." do
    pipe_through [:browser, :store]

    post "/:slug/payment/transbank", Store.PaymentController, :transbank, as: :transbank_payment
  end

  scope "/", Tq2Web do
    pipe_through [:browser, :csrf]

    get "/", RootController, :index
    get "/healthy", HealthController, :index

    resources(
      "/sessions",
      SessionController,
      only: [:new, :create, :delete],
      singleton: true
    )

    # Registration
    live "/registrations/new", Registration.NewLive, :index,
      as: "registration",
      session: @session_extras.registration

    get "/registrations/:uuid", RegistrationController, :show
    live "/tour", Registration.TourLive, :index
    live "/welcome", Registration.WelcomeLive, :index

    # Accounts
    resources "/accounts", AccountController, only: [:index, :show, :update]
    resources "/users", UserController
    resources "/passwords", PasswordController, only: [:new, :create, :edit, :update]
    live "/license", Account.LicenseLive, :index

    # Apps
    resources "/apps", AppController, param: "name"

    # Dashboard
    live "/dashboard", Dashboard.MainLive, :index, as: :dashboard

    # Inventories
    resources "/categories", CategoryController
    live "/items/new", Inventory.ItemLive, :new, session: @session_extras.current_session
    live "/items/:id/edit", Inventory.ItemLive, :edit, session: @session_extras.current_session
    resources "/items", ItemController, only: [:index, :show, :delete]
    live "/import", Inventory.ImportLive, :index
    live "/import/:section", Inventory.ImportOptionsLive, :show, as: :import

    # News
    resources "/notes", NoteController

    # Shops
    live "/store/edit/:section", Shop.StoreLive, :index, session: @session_extras.current_session

    # Sales
    resources "/orders", OrderController, only: [:index, :show]
    live "/orders/:id/edit", Order.OrderEditLive, :index, session: @session_extras.current_session

    live "/orders/:id/comments", Order.CommentLive, :index,
      session: @session_extras.current_session

    live "/orders/:id/payments", Order.PaymentLive, :index,
      as: :order_payment,
      session: @session_extras.current_session

    live "/carts", Cart.IndexLive, :index, session: @session_extras.current_session, as: :cart
    live "/carts/:id", Cart.ShowLive, :show, session: @session_extras.current_session, as: :cart
  end

  # Other scopes may use custom stacks.
  scope "/api", Tq2Web do
    pipe_through :api

    post "/webhooks/mercado_pago", WebhookController, :mercado_pago
    post "/webhooks/stripe", WebhookController, :stripe
  end

  if Application.get_env(:tq2, :env) == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Application.get_env(:tq2, :env) in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/phx-dashboard", metrics: Tq2Web.Telemetry
    end
  end
end

lib/tq2_web/live/account/license_live.ex
defmodule Tq2Web.Account.LicenseLive do
  use Tq2Web, :live_view

  import Tq2Web.Utils, only: [invert: 1, localize_date: 1]

  alias Tq2.Accounts
  alias Tq2.Accounts.License
  alias Tq2.Gateways.Stripe, as: StripeClient

  @statuses %{
    dgettext("licenses", "Trial") => "trial",
    dgettext("licenses", "Active") => "active",
    dgettext("licenses", "Unpaid") => "unpaid",
    dgettext("licenses", "Locked") => "locked",
    dgettext("licenses", "Canceled") => "canceled"
  }

  @impl true
  def mount(_, %{"account_id" => account_id, "user_id" => user_id}, socket) do
    session = Accounts.get_current_session(account_id, user_id)
    license = Accounts.get_license!(session.account)

    socket =
      socket
      |> assign(license: license, subscription: nil)
      |> trigger_fetch_subscription()

    {:ok, socket, temporary_assigns: [loading: false]}
  end

  @impl true
  def mount(_params, _session, socket) do
    socket =
      socket
      |> put_flash(:error, dgettext("sessions", "You must be logged in."))
      |> redirect(to: Routes.root_path(socket, :index))

    {:ok, socket}
  end

  @impl true
  def handle_event("monthly", _, socket) do
    socket = socket |> assign(loading: true)

    send(self(), {:monthly})

    {:noreply, socket}
  end

  @impl true
  def handle_event("yearly", _, socket) do
    socket = socket |> assign(loading: true)

    send(self(), {:yearly})

    {:noreply, socket}
  end

  @impl true
  def handle_event("customer-info", _, socket) do
    socket = socket |> assign(loading: true)

    send(self(), {:customer_info})

    {:noreply, socket}
  end

  @impl true
  def handle_info({:monthly}, socket) do
    socket = socket |> create_monthly_session()

    {:noreply, socket}
  end

  @impl true
  def handle_info({:yearly}, socket) do
    socket = socket |> create_yearly_session()

    {:noreply, socket}
  end

  @impl true
  def handle_info({:fetch_subscription}, socket) do
    socket = socket |> fetch_subscription()

    {:noreply, socket}
  end

  @impl true
  def handle_info({:customer_info}, socket) do
    socket = socket |> redirect_to_customer()

    {:noreply, socket}
  end

  defp create_monthly_session(%{assigns: %{license: %{customer_id: nil} = license}} = socket) do
    case StripeClient.create_customer(license) do
      %{customer_id: id} = license when is_binary(id) ->
        socket |> assign(license: license) |> create_monthly_session()

      _ ->
        socket |> put_flash(:error, dgettext("licenses", "Can't create subscription"))
    end
  end

  defp create_monthly_session(%{assigns: %{license: license}} = socket) do
    case StripeClient.create_subscription_session(license) do
      {:ok, id} ->
        socket
        |> assign(loading: true)
        |> push_event("redirect-to-checkout", %{id: id, key: public_key()})

      _ ->
        socket |> put_flash(:error, dgettext("licenses", "Can't create subscription"))
    end
  end

  defp create_yearly_session(%{assigns: %{license: %{customer_id: nil} = license}} = socket) do
    case StripeClient.create_customer(license) do
      %{customer_id: id} = license when is_binary(id) ->
        socket |> assign(license: license) |> create_yearly_session()

      _ ->
        socket |> put_flash(:error, dgettext("licenses", "Can't create subscription"))
    end
  end

  defp create_yearly_session(%{assigns: %{license: license}} = socket) do
    case StripeClient.create_subscription_session(license, :yearly) do
      {:ok, id} ->
        socket
        |> assign(loading: true)
        |> push_event("redirect-to-checkout", %{id: id, key: public_key()})

      _ ->
        socket |> put_flash(:error, dgettext("licenses", "Can't create subscription"))
    end
  end

  defp public_key do
    Application.get_env(:stripity_stripe, :public_key)
  end

  defp trigger_fetch_subscription(%{assigns: %{license: %{subscription_id: nil}}} = socket),
    do: socket

  defp trigger_fetch_subscription(socket) do
    send(self(), {:fetch_subscription})

    socket |> assign(loading: true)
  end

  defp fetch_subscription(%{assigns: %{license: license}} = socket) do
    case StripeClient.find_subscription(license) do
      nil ->
        socket
        |> put_flash(:error, dgettext("licenses", "Can't get your subscription"))

      subscription ->
        socket |> assign(subscription: subscription)
    end
  end

  defp redirect_to_customer(%{assigns: %{license: license}} = socket) do
    case StripeClient.create_billing_session(license) do
      {:ok, url} ->
        socket |> assign(loading: true) |> redirect(external: url)

      _ ->
        socket
        |> put_flash(:error, dgettext("licenses", "Can't get your subscription"))
    end
  end

  defp status(license) do
    statuses = invert(@statuses)

    statuses[license.status]
  end

  defp money(money), do: "#{money.currency} #{Money.to_string(money, symbol: true)}"

  defp subscription_info(%{loading: true}) do
    content_tag(:div, nil, class: "spinner-border text-primary")
  end

  defp subscription_info(%{license: %{subscription_id: nil} = license}) do
    [monthly_button(license), yearly_button(license)]
  end

  defp subscription_info(%{subscription: %{}}) do
    dgettext("licenses", "Show / modify subscription")
    |> link(to: "#", phx_click: "customer-info", class: "text-primary")
  end

  defp subscription_info(_assigns), do: nil

  defp monthly_button(license) do
    price = License.price_for(license)

    button =
      content_tag(:p, class: "mb-1") do
        dgettext("licenses", "Monthly pay %{money}", money: money(price))
        |> link(
          to: "#",
          phx_click: "monthly",
          class: "btn btn-outline-primary btn-lg rounded-pill px-3 border border-primary"
        )
      end

    text =
      content_tag(:p, class: "mb-3") do
        date =
          license.paid_until
          |> Timex.shift(months: 1)
          |> localize_date()

        content_tag(:span, dgettext("licenses", "Until %{date}", date: date), class: "text-muted")
      end

    [
      button,
      text
    ]
  end

  defp yearly_button(license) do
    price = License.price_for(license, :yearly)

    button =
      content_tag(:p, class: "mb-1") do
        dgettext("licenses", "Yearly pay %{money}", money: money(price))
        |> link(to: "#", phx_click: "yearly", class: "btn btn-primary btn-lg rounded-pill px-3")
      end

    text =
      content_tag(:p) do
        date =
          license.paid_until
          |> Timex.shift(years: 1)
          |> localize_date()

        content_tag(:span, dgettext("licenses", "Until %{date} Save two months!", date: date),
          class: "text-muted"
        )
      end

    [button, text]
  end

  defp subscription_plan(%{plan: plan}) do
    "#{translate_interval(plan.interval)} - #{money(Money.new(plan.amount, plan.currency))}"
  end

  defp translate_interval("month"), do: dgettext("licenses", "Monthly")
  defp translate_interval("year"), do: dgettext("licenses", "Yearly")
end

lib/tq2_web/live/cart/index_live.ex
defmodule Tq2Web.Cart.IndexLive do
  use Tq2Web, :live_view

  import Tq2Web.Utils, only: [localize_date: 1]
  import Tq2Web.Utils.Cart, only: [cart_total: 2]
  import Scrivener.HTML, only: [pagination_links: 3]

  alias Tq2.Transactions

  @impl true
  def mount(_, %{"current_session" => %{account: account}}, socket) do
    socket = socket |> assign(account: account)

    {:ok, socket}
  end

  @impl true
  def mount(_params, _session, socket) do
    socket =
      socket
      |> put_flash(:error, dgettext("sessions", "You must be logged in."))
      |> redirect(to: Routes.root_path(socket, :index))

    {:ok, socket}
  end

  @impl true
  def handle_params(params, _url, %{assigns: %{account: account}} = socket) do
    page = params["page"]
    carts = account |> Transactions.get_carts(%{page: page})
    socket = socket |> assign(carts: carts, page: page)

    {:noreply, socket}
  end

  defp link_to_show(socket, cart) do
    icon_link(
      "eye-fill",
      title: dgettext("cart", "Show"),
      to: Routes.cart_path(socket, :show, cart),
      class: "ml-2"
    )
  end
end

lib/tq2_web/live/cart/show_live.ex
defmodule Tq2Web.Cart.ShowLive do
  use Tq2Web, :live_view

  import Tq2.Utils.Urls, only: [store_uri: 0]
  import Tq2Web.Utils, only: [localize_date: 1]
  import Tq2Web.Utils.Cart, only: [cart_total: 2, line_price: 2, line_total: 3]

  alias Tq2.Shops
  alias Tq2.Transactions

  @impl true
  def mount(_, %{"current_session" => %{account: account}}, socket) do
    socket = socket |> assign(account: account)

    {:ok, socket}
  end

  @impl true
  def mount(_params, _session, socket) do
    socket =
      socket
      |> put_flash(:error, dgettext("sessions", "You must be logged in."))
      |> redirect(to: Routes.root_path(socket, :index))

    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _url, %{assigns: %{account: account}} = socket) do
    cart = account |> Transactions.get_cart!(id)
    store = account |> Shops.get_store!()
    account = %{account | store: store}
    socket = socket |> assign(account: account, cart: cart)

    {:noreply, socket}
  end

  @impl true
  def handle_event(
        "send-reminder",
        _params,
        %{assigns: %{account: account, cart: cart}} = socket
      ) do
    data =
      cart.data
      |> Transactions.Data.from_struct()
      |> Map.put(:notified_at, Timex.now())

    case Transactions.update_cart(account, cart, %{data: data}) do
      {:ok, updated_cart} ->
        cart = %{cart | data: updated_cart.data}
        socket = socket |> assign(:cart, cart)

        {:noreply, socket}

      {:error, _changeset} ->
        {:noreply, socket}
    end
  end

  defp cart_handing(%{data: %{handing: "pickup"}}), do: dgettext("orders", "Pickup")

  defp cart_handing(%{data: %{shipping: %{name: name}}}) do
    [dgettext("orders", "Delivery"), name] |> Enum.join(" | ")
  end

  defp cart_handing(_cart), do: nil

  defp cart_price_type("regular"), do: dgettext("carts", "Regular")

  defp cart_price_type("promotional") do
    content_tag(:span, dgettext("carts", "Teiqui"), class: "text-primary")
  end

  defp resume_cart_url(store, %{id: id}) do
    store_uri() |> Routes.cart_url(:show, store, id)
  end

  defp can_be_notified?(%{data: %{notified_at: %DateTime{} = notified_at}}) do
    DateTime.utc_now()
    |> Timex.shift(hours: -1)
    |> DateTime.compare(notified_at)
    |> Kernel.==(:gt)
  end

  defp can_be_notified?(_), do: true
end

lib/tq2_web/live/components/button_component.ex
defmodule Tq2Web.ButtonComponent do
  use Tq2Web, :live_component

  alias Tq2.Transactions.Cart

  def cart_total(%Cart{} = cart) do
    cart
    |> amounts()
    |> Enum.reduce(fn price, total -> Money.add(price, total) end)
    |> Money.to_string(symbol: true)
  end

  defp show_button?(%{lines: []}), do: false
  defp show_button?(_), do: true

  defp amounts(%Cart{price_type: "promotional", lines: lines}) do
    Enum.map(lines, &Money.multiply(&1.promotional_price, &1.quantity))
  end

  defp amounts(%Cart{price_type: "regular", lines: lines}) do
    Enum.map(lines, &Money.multiply(&1.price, &1.quantity))
  end
end

lib/tq2_web/live/components/dashboard/items_tour_component.ex
defmodule Tq2Web.Dashboard.ItemsTourComponent do
  use Tq2Web, :live_component
end

lib/tq2_web/live/components/dashboard/tour_component.ex
defmodule Tq2Web.Dashboard.TourComponent do
  use Tq2Web, :live_component
end

lib/tq2_web/live/components/item/promotional_price_component.ex
defmodule Tq2Web.Item.PromotionalPriceComponent do
  use Tq2Web, :live_component
end

lib/tq2_web/live/dashboard/main_live.html.leex
<div id="dashboard" class="row justify-content-center mt-n2 mb-n3" phx-hook="BodyBackground" data-bg-class="bg-primary">
  <div id="dashboard-container" class="col-md-8">
    <%= live_component @socket, NotificationComponent, id: :notification, user_id: @user_id do %>
      <%= dgettext("notifications", "Do you want to receive notifications about orders and other actions?") %>
    <% end %>

    <%= unpublished_store_alert @store %>

    <p class="small text-light float-right mt-3 mr-3 pt-1">
      <%= dgettext("dashboard", "Today") %>
    </p>

    <h2 class="h4 font-weight-semi-bold text-light mt-3 ml-3">
      <%= dgettext("dashboard", "Sales") %>
    </h2>

    <div class="card card-body py-2 mb-3 mt-2">
      <%= if Money.zero?(@amount) do %>
        <p class="h5 text-info mt-3 mb-0">
          <%= dgettext("dashboard", "You have no orders yet.") %>
        </p>
      <% else %>
        <p class="h3 text-info font-weight-semi-bold py-2 mb-0">
          <%= Money.to_string(@amount, symbol: true) %>
        </p>
      <% end %>

      <p class="text-info mb-0">
        <%= dgettext("dashboard", "Share your store to get some orders.") %>
      </p>

      <%= live_component @socket, ShareComponent, id: :header,
                                                  store: @store,
                                                  token: "dashboard",
                                                  class: "btn btn-lg btn-block btn-info font-weight-semi-bold my-3",
                                                  align_right: false do %>
        <span class="float-left mr-n3">
          <i class="bi-share-fill"></i>
        </span>
        <%= dgettext("dashboard", "Spread my store") %>
      <% end %>
    </div>

    <p class="small text-light float-right mr-3 pt-1">
      <%= dgettext("dashboard", "Today") %>
    </p>

    <h2 class="h4 font-weight-semi-bold text-light mt-3 ml-3">
      <%= dgettext("dashboard", "Dashboard") %>
    </h2>

    <div class="card card-body mb-3 mt-2">
      <p class="float-right text-right text-muted small mb-0 mb-n3">
        <%= dgettext("dashboard", "All channels") %>
      </p>

      <h4 class="h5 text-primary mb-2">
        <%= dgettext("dashboard", "Store visits") %>
      </h4>

      <p class="lead font-weight-semi-bold mb-0">
        <%= current_visits @visits %>
      </p>

      <h4 class="h5 text-primary mb-2 mt-4">
        <%= dgettext("dashboard", "Sales") %>
      </h4>

      <div class="row">
        <div class="col-6">
          <h5 class="h6">
            <%= dgettext("dashboard", "Teiqui price") %>
          </h5>
          <p class="lead mb-0">
            <%= count(@counts, "promotional", "finished") %>
          </p>
        </div>
        <div class="col-6">
          <h5 class="h6">
            <%= dgettext("dashboard", "Regular") %>
          </h5>
          <p class="lead mb-0">
            <%= count(@counts, "regular", "finished") %>
          </p>
        </div>
      </div>

      <h3 class="h5 text-primary mb-2 mt-4">
        <%= dgettext("dashboard", "Performance") %>
      </h3>

      <p class="mb-0">
        <%= performance @visits %>
        <%= performance_hint @visits %>
      </p>
    </div>

    <div class="card card-body my-3 pb-3">
      <div class="row">
        <div class="col-8">
          <h3 class="h5 text-primary mb-3">
            <%= dgettext("orders", "Orders") %>
          </h3>
        </div>
        <div class="col-4">
          <p class="text-right text-muted small mb-0">
            <%= link dgettext("dashboard", "Go to orders"), to: Routes.order_path(@socket, :index),
                                                            class: "text-info" %>
          </p>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <h4 class="h6">
            <%= dgettext("dashboard", "Pending") %>
          </h4>
          <p class="lead font-weight-bold mb-0">
            <%= count(@counts, "regular", "pending") + count(@counts, "promotional", "pending") %>
          </p>
        </div>
        <div class="col-6">
          <h4 class="h6">
            <%= dgettext("dashboard", "Finished") %>
          </h4>
          <p class="lead font-weight-bold mb-0">
            <%= count(@counts, "regular", "finished") + count(@counts, "promotional", "finished") %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<%= if assigns[:tour] == "dashboard" do %>
  <%= live_component @socket, TourComponent %>
<% end %>

<%= if assigns[:tour] == "items" do %>
  <%= live_component @socket, ItemsTourComponent %>
<% end %>