lib/tq2_web/router.ex
defmodule Tq2Web.Router do
  use Tq2Web, :router

  @session_extras %{
    current_session: {Tq2Web.SessionPlug, :session_extras, [:current_session]},
    registration: {Tq2Web.SessionPlug, :session_extras, [:registration]},
    store: {Tq2Web.SessionPlug, :session_extras, [:store]}
  }

  pipeline :csrf do
    plug :protect_from_forgery
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :fetch_current_session
    plug :check_locked_license
    plug :put_root_layout, {Tq2Web.LayoutView, :root}
    plug :put_secure_browser_headers
    plug :put_cache_control_headers

    if Application.get_env(:tq2, :env) == :prod do
      plug Tq2Web.SSLPlug,
        host: nil,
        hsts: true,
        preload: true,
        subdomains: true,
        rewrite_on: [:x_forwarded_proto]
    end
  end

  pipeline :store do
    plug :fetch_store
    plug :fetch_token
    plug :track_visit
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :put_cache_control_headers
  end

  pipeline :pwa do
    plug :accepts, ["html", "json", "js"]
    plug :put_secure_browser_headers
    plug :put_cache_control_headers
  end

  scope "/", Tq2Web, host: Application.get_env(:tq2, :web_host) do
    pipe_through :browser

    get "/", PageController, :index
    get "/terms", LegalController, :index
    get "/:country", PageController, :index
  end

  scope "/", Tq2Web do
    pipe_through :pwa

    get "/service-worker.js", PwaController, :service_worker
    get "/manifest.json", PwaController, :manifest
    get "/offline.html", PwaController, :offline
  end

  scope "/", Tq2Web, host: "#{Application.get_env(:tq2, :store_subdomain)}." do
    pipe_through [:browser, :csrf, :store]

    put "/:slug/session/dismiss_price_info", Store.SessionController, :dismiss_price_info,
      as: :store_dismiss_price_info

    live "/:slug", Store.CounterLive, :index, session: @session_extras.store
    live "/:slug/items/:id", Store.ItemLive, :index, session: @session_extras.store
    live "/:slug/handing", Store.HandingLive, :index, session: @session_extras.store
    live "/:slug/customer", Store.CustomerLive, :index, session: @session_extras.store
    live "/:slug/payment", Store.PaymentLive, :index, session: @session_extras.store
    live "/:slug/payment/check", Store.PaymentCheckLive, :index, session: @session_extras.store
    live "/:slug/order/:id", Store.OrderLive, :index, session: @session_extras.store
    live "/:slug/team", Store.TeamLive, :index, session: @session_extras.store
    live "/:slug/checkout", Store.CheckoutLive, :index, session: @session_extras.store
    live "/:slug/brief", Store.BriefLive, :index, session: @session_extras.store

    get "/:slug/tokens/:token", TokenController, :show
    get "/:slug/cart/:from", CartController, :show
  end

  scope "/", Tq2Web, host: "#{Application.get_env(:tq2, :store_subdomain)}." do
    pipe_through [:browser, :store]

    post "/:slug/payment/transbank", Store.PaymentController, :transbank, as: :transbank_payment
  end

  scope "/", Tq2Web do
    pipe_through [:browser, :csrf]

    get "/", RootController, :index
    get "/healthy", HealthController, :index

    resources(
      "/sessions",
      SessionController,
      only: [:new, :create, :delete],
      singleton: true
    )

    # Registration
    live "/registrations/new", Registration.NewLive, :index,
      as: "registration",
      session: @session_extras.registration

    get "/registrations/:uuid", RegistrationController, :show
    live "/tour", Registration.TourLive, :index
    live "/welcome", Registration.WelcomeLive, :index

    # Accounts
    resources "/accounts", AccountController, only: [:index, :show, :update]
    resources "/users", UserController
    resources "/passwords", PasswordController, only: [:new, :create, :edit, :update]
    live "/license", Account.LicenseLive, :index

    # Apps
    resources "/apps", AppController, param: "name"

    # Dashboard
    live "/dashboard", Dashboard.MainLive, :index, as: :dashboard

    # Inventories
    resources "/categories", CategoryController
    live "/items/new", Inventory.ItemLive, :new, session: @session_extras.current_session
    live "/items/:id/edit", Inventory.ItemLive, :edit, session: @session_extras.current_session
    resources "/items", ItemController, only: [:index, :show, :delete]
    live "/import", Inventory.ImportLive, :index
    live "/import/:section", Inventory.ImportOptionsLive, :show, as: :import

    # News
    resources "/notes", NoteController

    # Shops
    live "/store/edit/:section", Shop.StoreLive, :index, session: @session_extras.current_session

    # Sales
    resources "/orders", OrderController, only: [:index, :show]
    live "/orders/:id/edit", Order.OrderEditLive, :index, session: @session_extras.current_session

    live "/orders/:id/comments", Order.CommentLive, :index,
      session: @session_extras.current_session

    live "/orders/:id/payments", Order.PaymentLive, :index,
      as: :order_payment,
      session: @session_extras.current_session

    live "/carts", Cart.IndexLive, :index, session: @session_extras.current_session, as: :cart
    live "/carts/:id", Cart.ShowLive, :show, session: @session_extras.current_session, as: :cart
  end

  # Other scopes may use custom stacks.
  scope "/api", Tq2Web do
    pipe_through :api

    post "/webhooks/mercado_pago", WebhookController, :mercado_pago
    post "/webhooks/stripe", WebhookController, :stripe
  end

  if Application.get_env(:tq2, :env) == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Application.get_env(:tq2, :env) in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/phx-dashboard", metrics: Tq2Web.Telemetry
    end
  end
end

lib/tq2/accounts/password.ex
defmodule Tq2.Accounts.Password do
  import Ecto.Query

  alias Tq2.Accounts.User
  alias Tq2.Notifications
  alias Tq2.{Repo, Trail}

  def get_user_by_token(token) do
    user_by_token =
      from(u in User,
        where: u.password_reset_token == ^token,
        where: u.password_reset_sent_at >= ago(6, "hour")
      )

    Repo.one(user_by_token)
  end

  def reset(%User{} = user) do
    {:ok, user_with_token} =
      user
      |> User.password_reset_token_changeset()
      |> Trail.update()

    Notifications.send_password_reset(user_with_token)

    {:ok, user_with_token}
  end
end

lib/tq2_web/controllers/password_controller.ex
defmodule Tq2Web.PasswordController do
  use Tq2Web, :controller

  alias Tq2.Accounts
  alias Tq2.Accounts.{Password, User}

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email}}) do
    case Accounts.get_user(email: email) do
      %User{} = user ->
        {:ok, _} = Password.reset(user)

        conn
        |> put_flash(:info, dgettext("passwords", "Password reset instructions sent"))
        |> redirect(to: Routes.root_path(conn, :index))

      nil ->
        conn
        |> put_flash(:error, dgettext("passwords", "Email not found"))
        |> render("new.html")
    end
  end

  def edit(conn, %{"id" => token}) do
    case Accounts.get_user(token: token) do
      %User{} = user ->
        changeset = Accounts.change_user_password(user)

        render(conn, "edit.html", token: token, changeset: changeset)

      nil ->
        handle_invalid_token(conn)
    end
  end

  def update(conn, %{"id" => token, "user" => password_params}) do
    case Accounts.get_user(token: token) do
      %User{} = user ->
        case Accounts.update_user_password(user, password_params) do
          {:ok, _} ->
            conn
            |> put_flash(:info, dgettext("passwords", "Password updated successfully"))
            |> redirect(to: Routes.root_path(conn, :index))

          {:error, %Ecto.Changeset{} = changeset} ->
            render(conn, "edit.html", token: token, changeset: changeset)
        end

      nil ->
        handle_invalid_token(conn)
    end
  end

  defp handle_invalid_token(conn) do
    conn
    |> put_flash(:error, dgettext("passwords", "Token invalid or expired"))
    |> redirect(to: Routes.root_path(conn, :index))
  end
end

lib/tq2_web/views/password_view.ex
defmodule Tq2Web.PasswordView do
  use Tq2Web, :view
end

lib/tq2_web/templates/password/edit.html.eex
<div class="row justify-content-center">
  <div class="col-lg-4 col-md-6 col-sm-8 text-center">
    <div class="pb-5 mt-4">
      <%= link to: Routes.root_path(@conn, :index) do %>
        <%= img_tag Routes.static_path(@conn, "/images/logo.svg"), width: "101", height: "26", alt: gettext("Teiqui") %>
      <% end %>
    </div>

    <h2 class="h5 text-primary mt-4 mb-3 font-weight-semi-bold">
      <%= dgettext("passwords", "Change password") %>
    </h2>

    <p class="text-muted mb-4">
      <%= dgettext("passwords", "Enter your new password") %>
    </p>

    <%= form_for @changeset, Routes.password_path(@conn, :update, @token), [as: :user, method: :patch, class: "px-3"], fn f -> %>
      <%= input f, :password, dgettext("users", "Password"),
        input_html: [
          autofocus: true,
          autocomplete: "new-password",
          placeholder: dgettext("users", "Password")
        ],
        label_html: [class: "sr-only"] %>

      <%= input f, :password_confirmation, dgettext("users", "Password confirmation"),
        wrapper_html: [class: "pb-3"],
        input_html: [autocomplete: "new-password", placeholder: dgettext("users", "Password confirmation")],
        label_html: [class: "sr-only"] %>

      <div class="form-actions text-center my-5">
        <%= submit dgettext("passwords", "Update password"),
          class: "btn btn-primary rounded-pill px-5 font-weight-semi-bold" %>
      </div>
    <% end %>
  </div>
</div>

lib/tq2_web/templates/password/new.html.eex
<div class="row justify-content-center">
  <div class="col-lg-4 col-md-6 col-sm-8 text-center">
    <div class="pb-5 mt-4">
      <%= link to: Routes.root_path(@conn, :index) do %>
        <%= img_tag Routes.static_path(@conn, "/images/logo.svg"), width: "101", height: "26", alt: gettext("Teiqui") %>
      <% end %>
    </div>

    <h2 class="h5 text-primary mt-4 mb-3 font-weight-semi-bold">
      <%= dgettext("passwords", "Restore password") %>
    </h2>

    <p class="text-muted mb-5">
      <%= dgettext("passwords", "Enter your email address and we'll send you the recovery instructions") %>
    </p>

    <%= form_for @conn, Routes.password_path(@conn, :create), [as: :user, class: "px-3"], fn f -> %>
      <%= input f, :email, dgettext("users", "Email"),
        wrapper_html: [class: "pb-3"],
        input_html: [autofocus: true, autocomplete: "off", placeholder: dgettext("users", "Email")],
        label_html: [class: "sr-only"] %>

      <div class="form-actions text-center mt-5 mb-3">
        <%= submit dgettext("passwords", "Send instructions"),
          class: "btn btn-primary rounded-pill px-5 font-weight-semi-bold" %>
      </div>
    <% end %>

    <p class="mt-3 text-center font-weight-semi-bold mt-4 mb-3 mb-md-5">
      <%= link dgettext("passwords", "Go back"), to: Routes.session_path(@conn, :new) %>
    </p>
  </div>
</div>