lib/tq2_web/router.ex
defmodule Tq2Web.Router do
  use Tq2Web, :router

  @session_extras %{
    current_session: {Tq2Web.SessionPlug, :session_extras, [:current_session]},
    registration: {Tq2Web.SessionPlug, :session_extras, [:registration]},
    store: {Tq2Web.SessionPlug, :session_extras, [:store]}
  }

  pipeline :csrf do
    plug :protect_from_forgery
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :fetch_current_session
    plug :check_locked_license
    plug :put_root_layout, {Tq2Web.LayoutView, :root}
    plug :put_secure_browser_headers
    plug :put_cache_control_headers

    if Application.get_env(:tq2, :env) == :prod do
      plug Tq2Web.SSLPlug,
        host: nil,
        hsts: true,
        preload: true,
        subdomains: true,
        rewrite_on: [:x_forwarded_proto]
    end
  end

  pipeline :store do
    plug :fetch_store
    plug :fetch_token
    plug :track_visit
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :put_cache_control_headers
  end

  pipeline :pwa do
    plug :accepts, ["html", "json", "js"]
    plug :put_secure_browser_headers
    plug :put_cache_control_headers
  end

  scope "/", Tq2Web, host: Application.get_env(:tq2, :web_host) do
    pipe_through :browser

    get "/", PageController, :index
    get "/terms", LegalController, :index
    get "/:country", PageController, :index
  end

  scope "/", Tq2Web do
    pipe_through :pwa

    get "/service-worker.js", PwaController, :service_worker
    get "/manifest.json", PwaController, :manifest
    get "/offline.html", PwaController, :offline
  end

  scope "/", Tq2Web, host: "#{Application.get_env(:tq2, :store_subdomain)}." do
    pipe_through [:browser, :csrf, :store]

    put "/:slug/session/dismiss_price_info", Store.SessionController, :dismiss_price_info,
      as: :store_dismiss_price_info

    live "/:slug", Store.CounterLive, :index, session: @session_extras.store
    live "/:slug/items/:id", Store.ItemLive, :index, session: @session_extras.store
    live "/:slug/handing", Store.HandingLive, :index, session: @session_extras.store
    live "/:slug/customer", Store.CustomerLive, :index, session: @session_extras.store
    live "/:slug/payment", Store.PaymentLive, :index, session: @session_extras.store
    live "/:slug/payment/check", Store.PaymentCheckLive, :index, session: @session_extras.store
    live "/:slug/order/:id", Store.OrderLive, :index, session: @session_extras.store
    live "/:slug/team", Store.TeamLive, :index, session: @session_extras.store
    live "/:slug/checkout", Store.CheckoutLive, :index, session: @session_extras.store
    live "/:slug/brief", Store.BriefLive, :index, session: @session_extras.store

    get "/:slug/tokens/:token", TokenController, :show
    get "/:slug/cart/:from", CartController, :show
  end

  scope "/", Tq2Web, host: "#{Application.get_env(:tq2, :store_subdomain)}." do
    pipe_through [:browser, :store]

    post "/:slug/payment/transbank", Store.PaymentController, :transbank, as: :transbank_payment
  end

  scope "/", Tq2Web do
    pipe_through [:browser, :csrf]

    get "/", RootController, :index
    get "/healthy", HealthController, :index

    resources(
      "/sessions",
      SessionController,
      only: [:new, :create, :delete],
      singleton: true
    )

    # Registration
    live "/registrations/new", Registration.NewLive, :index,
      as: "registration",
      session: @session_extras.registration

    get "/registrations/:uuid", RegistrationController, :show
    live "/tour", Registration.TourLive, :index
    live "/welcome", Registration.WelcomeLive, :index

    # Accounts
    resources "/accounts", AccountController, only: [:index, :show, :update]
    resources "/users", UserController
    resources "/passwords", PasswordController, only: [:new, :create, :edit, :update]
    live "/license", Account.LicenseLive, :index

    # Apps
    resources "/apps", AppController, param: "name"

    # Dashboard
    live "/dashboard", Dashboard.MainLive, :index, as: :dashboard

    # Inventories
    resources "/categories", CategoryController
    live "/items/new", Inventory.ItemLive, :new, session: @session_extras.current_session
    live "/items/:id/edit", Inventory.ItemLive, :edit, session: @session_extras.current_session
    resources "/items", ItemController, only: [:index, :show, :delete]
    live "/import", Inventory.ImportLive, :index
    live "/import/:section", Inventory.ImportOptionsLive, :show, as: :import

    # News
    resources "/notes", NoteController

    # Shops
    live "/store/edit/:section", Shop.StoreLive, :index, session: @session_extras.current_session

    # Sales
    resources "/orders", OrderController, only: [:index, :show]
    live "/orders/:id/edit", Order.OrderEditLive, :index, session: @session_extras.current_session

    live "/orders/:id/comments", Order.CommentLive, :index,
      session: @session_extras.current_session

    live "/orders/:id/payments", Order.PaymentLive, :index,
      as: :order_payment,
      session: @session_extras.current_session

    live "/carts", Cart.IndexLive, :index, session: @session_extras.current_session, as: :cart
    live "/carts/:id", Cart.ShowLive, :show, session: @session_extras.current_session, as: :cart
  end

  # Other scopes may use custom stacks.
  scope "/api", Tq2Web do
    pipe_through :api

    post "/webhooks/mercado_pago", WebhookController, :mercado_pago
    post "/webhooks/stripe", WebhookController, :stripe
  end

  if Application.get_env(:tq2, :env) == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Application.get_env(:tq2, :env) in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/phx-dashboard", metrics: Tq2Web.Telemetry
    end
  end
end

lib/tq2_web/controllers/store/payment_controller.ex
defmodule Tq2Web.Store.PaymentController do
  use Tq2Web, :controller

  alias Tq2.Gateways.Transbank
  alias Tq2.Payments
  alias Tq2.Payments.Payment
  alias Tq2.Transactions.Cart

  @doc """
  Controller without CSRF protection.

  These actions are called from a vendor modal iframe.
  """

  def action(%{assigns: %{store: store}} = conn, _) do
    session = %{store: store}

    apply(__MODULE__, action_name(conn), [conn, conn.params, session])
  end

  def transbank(conn, %{"id" => id, "channel" => channel}, %{store: store}) do
    cart = store.account |> Tq2.Transactions.get_cart!(id)

    cart
    |> get_payment()
    |> create_preference(cart, channel, store)
    |> respond_with_payment(conn)
  end

  defp create_preference(nil, _cart, _channel, _store), do: nil

  defp create_preference(%Payment{} = payment, cart, channel, store) do
    payment = %{payment | cart: cart}

    store.account
    |> Tq2.Apps.get_app("transbank")
    |> create_full_or_partial_preference(payment, cart, store, channel)
    |> maybe_update_payment(cart, payment)
  end

  defp create_full_or_partial_preference(app, payment, cart, store, channel) do
    case payment.amount == Cart.total(cart) do
      true ->
        Transbank.create_cart_preference(app, cart, store, channel)

      false ->
        Transbank.create_partial_preference(app, payment, store, channel)
    end
  end

  defp maybe_update_payment(%{"responseCode" => "OK", "result" => result}, cart, payment) do
    payment = %{payment | cart: cart}
    attrs = %{external_id: result["externalUniqueNumber"], gateway_data: result}

    case Tq2.Payments.update_payment(cart, payment, attrs) do
      {:ok, payment} ->
        payment

      {:error, changeset} ->
        Sentry.capture_message("[Tbk] Payment update", extra: changeset.errors)

        nil
    end
  end

  defp maybe_update_payment(_response, _cart, _payment), do: nil

  defp respond_with_payment(
         %Payment{gateway_data: %{} = result, amount: %{amount: amount}},
         conn
       ) do
    attrs = result |> Map.put("amount", amount) |> Map.delete("signature")

    json(conn, attrs)
  end

  defp respond_with_payment(_payment, conn), do: json(conn, %{})

  defp get_payment(nil), do: nil

  defp get_payment(cart) do
    cart |> Payments.get_pending_payment_for_cart_and_kind("transbank")
  end
end

lib/tq2_web/controllers/store/session_controller.ex
defmodule Tq2Web.Store.SessionController do
  use Tq2Web, :controller

  @doc """
  Controller to manage session for live views.
  """

  def dismiss_price_info(conn, _params) do
    conn = put_session(conn, :hide_price_info, true)

    json(conn, %{})
  end
end

lib/tq2_web/live/components/button_component.ex
defmodule Tq2Web.ButtonComponent do
  use Tq2Web, :live_component

  alias Tq2.Transactions.Cart

  def cart_total(%Cart{} = cart) do
    cart
    |> amounts()
    |> Enum.reduce(fn price, total -> Money.add(price, total) end)
    |> Money.to_string(symbol: true)
  end

  defp show_button?(%{lines: []}), do: false
  defp show_button?(_), do: true

  defp amounts(%Cart{price_type: "promotional", lines: lines}) do
    Enum.map(lines, &Money.multiply(&1.promotional_price, &1.quantity))
  end

  defp amounts(%Cart{price_type: "regular", lines: lines}) do
    Enum.map(lines, &Money.multiply(&1.price, &1.quantity))
  end
end

lib/tq2_web/live/components/dashboard/items_tour_component.ex
defmodule Tq2Web.Dashboard.ItemsTourComponent do
  use Tq2Web, :live_component
end

lib/tq2_web/live/components/dashboard/tour_component.ex
defmodule Tq2Web.Dashboard.TourComponent do
  use Tq2Web, :live_component
end

lib/tq2_web/live/components/header_component.ex
defmodule Tq2Web.HeaderComponent do
  use Tq2Web, :live_component

  alias Tq2.Shops.Store

  defp image(%Store{logo: nil}) do
  end

  defp image(%Store{logo: logo} = store) do
    url = Tq2.LogoUploader.url({logo, store}, :thumb)

    set = %{
      url => "1x",
      Tq2.LogoUploader.url({logo, store}, :thumb_2x) => "2x"
    }

    img_tag(url,
      srcset: set,
      width: "70",
      height: "70",
      loading: "lazy",
      alt: store.name,
      class: "img-fluid rounded-circle"
    )
  end
end

lib/tq2_web/live/components/import/headers_component.ex
defmodule Tq2Web.Import.HeadersComponent do
  use Tq2Web, :live_component

  @impl true
  def handle_event(
        "import",
        %{"import" => %{"name" => _} = attrs},
        %{assigns: %{column_titles: column_titles, sheet_id: sheet_id}} = socket
      ) do
    socket =
      attrs
      |> valid_attrs?(column_titles)
      |> maybe_import(sheet_id, attrs, column_titles, socket)

    {:noreply, socket}
  end

  defp collection_options(column_titles) do
    [
      collection: column_titles,
      input_html: [prompt: dgettext("items", "None")]
    ]
  end

  defp submit_import do
    enable_text = dgettext("items", "Import")
    disable_text = dgettext("items", "Importing...")

    submit(enable_text,
      class: "btn btn-lg btn-block btn-primary",
      phx_disable_with: disable_text
    )
  end

  defp import_sheet(socket, sheet_id, attrs, column_titles) do
    headers =
      attrs
      |> Enum.filter(fn {_, v} -> v && String.length(v) > 0 end)
      |> Enum.map(fn {k, v} ->
        index = Enum.find_index(column_titles, fn name -> name == v end)

        {String.to_atom(k), index}
      end)
      |> Map.new()

    opts = %{
      headers_with_index: headers,
      sheet_id: sheet_id
    }

    send(self(), {:import, opts})

    socket
  end

  defp valid_attrs?(
         %{"name" => name, "price" => price, "promotional_price" => promotional_price},
         column_titles
       ) do
    Enum.all?(
      [name, price, promotional_price],
      fn value -> is_binary(value) && value in column_titles end
    )
  end

  defp valid_attrs?(_attrs, _column_titles), do: false

  defp maybe_import(true, sheet_id, attrs, column_titles, socket) do
    socket |> import_sheet(sheet_id, attrs, column_titles)
  end

  defp maybe_import(_, _sheet_id, _attrs, _column_titles, socket) do
    socket |> put_flash(:error, dgettext("items", "Need at least Name, Price and Teiqui price"))
  end
end

lib/tq2_web/live/components/import/predefined_component.ex
defmodule Tq2Web.Import.PredefinedComponent do
  use Tq2Web, :live_component

  def put_component_assigns(%{assigns: %{grid_titles: [_ | _]}} = socket), do: socket

  def put_component_assigns(socket) do
    socket |> assign(grid_titles: grid_titles())
  end

  @impl true
  def handle_event("import", %{"import" => %{"grid_title" => title}}, socket) do
    opts = %{
      grid_title: title,
      sheet_id: default_sheet_id()
    }

    send(self(), {:import, opts})

    {:noreply, socket}
  end

  defp default_sheet_id do
    :tq2 |> Application.get_env(:default_sheet_id)
  end

  defp submit_import do
    enable_text = dgettext("items", "Import")
    disable_text = dgettext("items", "Importing...")

    submit(enable_text,
      class: "btn btn-lg btn-block btn-primary",
      phx_disable_with: disable_text
    )
  end

  defp grid_titles do
    default_sheet_id()
    |> Tq2.Gdrive.grid_titles()
    |> Enum.sort()
  end

  defp grid_title_prompt do
    dgettext("items", "Select store type...")
  end
end

lib/tq2_web/live/components/import/upload_component.ex
defmodule Tq2Web.Import.UploadComponent do
  use Tq2Web, :live_component

  @mime_types ~w(
    text/csv
    application/vnd.ms-excel
    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    application/vnd.oasis.opendocument.spreadsheet
  )

  def put_component_assigns(socket) do
    socket
    |> allow_upload(:file,
      accept: @mime_types,
      max_entries: 1,
      auto_upload: true,
      progress: &handle_upload/3
    )
  end

  @impl true
  def handle_event("validate", _params, socket), do: {:noreply, socket}

  defp handle_upload(:file, entry, socket) do
    if entry.done? do
      consume_uploaded_entries(socket, :file, fn meta, entry ->
        path = "#{meta.path}-#{entry.client_name}"

        File.cp!(meta.path, path)

        self() |> send({:upload_file, path})
      end)
    end

    socket = socket |> assign(uploading: true)

    {:noreply, socket}
  end
end

lib/tq2_web/live/components/import/url_component.ex
defmodule Tq2Web.Import.UrlComponent do
  use Tq2Web, :live_component

  def put_component_assigns(socket) do
    socket |> assign(:sheet_id, nil)
  end

  @impl true
  def handle_event("read", %{"read" => %{"url" => url}}, socket) do
    parsed_sheet_id = url |> sheet_id_from_url()
    socket = socket |> read_sheet_titles(parsed_sheet_id)

    {:noreply, socket}
  end

  defp sheet_id_from_url(url) do
    Regex.run(
      ~r/docs\.google\.com\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/,
      url,
      capture: :all_but_first
    )
  end

  defp read_sheet_titles(socket, nil) do
    socket |> put_flash(:error, dgettext("items", "Can't read spreadsheet"))
  end

  defp read_sheet_titles(socket, [sheet_id]) do
    self() |> send({:read_titles, sheet_id})

    socket
  end

  defp submit_import do
    enable_text = dgettext("items", "Read")
    disable_text = dgettext("items", "Reading...")

    submit(enable_text,
      class: "btn btn-lg btn-block btn-primary",
      phx_disable_with: disable_text
    )
  end
end

lib/tq2_web/live/components/item/promotional_price_component.ex
defmodule Tq2Web.Item.PromotionalPriceComponent do
  use Tq2Web, :live_component
end

lib/tq2_web/live/components/item/tour_component.ex
defmodule Tq2Web.Item.TourComponent do
  use Tq2Web, :live_component
end

lib/tq2_web/live/components/order/payment_component.ex
defmodule Tq2Web.Order.PaymentComponent do
  use Tq2Web, :live_component

  import Tq2Web.OrderView, only: [format_money: 1, payment_kind: 1]

  defp link_to_delete(payment) do
    icon_link(
      "backspace-reverse",
      to: "#",
      phx_click: "delete",
      phx_value_id: payment.id,
      phx_target: "#payments-component"
    )
  end
end

lib/tq2_web/live/components/order/payment_form_component.ex
defmodule Tq2Web.Order.PaymentFormComponent do
  use Tq2Web, :live_component

  defp payment_methods do
    [
      {"cash", dgettext("payments", "Cash")},
      {"wire_transfer", dgettext("payments", "Wire transfer")},
      {"other", dgettext("payments", "Other")}
    ]
  end

  defp payment_kind?(%{changes: %{kind: kind}}, kind), do: true
  defp payment_kind?(_, _kind), do: false

  defp submit_payment(%{valid?: true}) do
    dgettext("payments", "Create payment")
    |> submit(class: "btn btn-primary rounded-pill font-weight-bold py-2")
  end

  defp submit_payment(_), do: nil

  defp static_img(kind, text) do
    img_tag(
      Routes.static_path(Tq2Web.Endpoint, "/images/#{kind}.png"),
      alt: text,
      width: "20",
      height: "20",
      class: "img-fluid mr-3"
    )
  end
end

lib/tq2_web/live/components/store/button_component.ex
defmodule Tq2Web.Store.ButtonComponent do
  use Tq2Web, :live_component

  alias Tq2Web.Store.{OptionsComponent, ShareComponent}

  defp show_button?(%{lines: []}), do: false
  defp show_button?(_), do: true

  defp button_wrapper(%{to: to, enabled: enabled}, do: block) do
    live_redirect(to: to, class: link_button_classes(enabled), do: block)
  end

  defp button_wrapper(%{enabled: enabled, disable_with: disable_with}, do: block) do
    submit(
      [
        class: link_button_classes(true),
        phx_disable_with: disable_with,
        disabled: !enabled
      ],
      do: block
    )
  end

  defp link_button_classes(true) do
    "btn btn-block btn-lg btn-primary"
  end

  defp link_button_classes(_) do
    "btn btn-block btn-lg btn-primary disabled"
  end
end

lib/tq2_web/live/components/store/button_component.html.leex
<%= if show_button?(@cart) do %>
  <nav class="fixed-bottom bg-white pb-1">
    <div class="container-fluid pb-1 pt-2">
      <div class="d-flex">
        <div class="mr-2">
          <%= live_component @socket, OptionsComponent, store: @store %>
        </div>

        <div class="flex-fill">
          <%= button_wrapper assigns do %>
            <span class="d-flex">
              <span>
                <i class="bi-cart3"></i>
              </span>

              <span class="flex-fill">
                <%= render_block(@inner_block) %>
              </span>
            </span>
          <% end %>
        </div>

        <div class="ml-2">
          <%= live_component @socket, ShareComponent, id: :button,
                                                      store: @store,
                                                      token: @token,
                                                      class: "btn btn-primary btn-lg py-2",
                                                      align_right: true do %>
            <i class="bi-share-fill"></i>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
<% end %>

lib/tq2_web/live/components/store/category_component.html.leex
<%= live_patch to: Routes.counter_path(@socket, :index, @store, category: @id),
               class: "col text-decoration-none",
               id: "category-#{@id}", phx_hook: "ScrollToTop" do %>
  <div class="card mx-2 my-3 position-relative shadow bg-<%= if @selected, do: "secondary", else: "white" %>">
    <div class="card-body p-1">
      <%= image_for @category %>
    </div>
  </div>

  <p class="h5 text-center text-truncate text-dark font-weight-semi-bold my-3">
    <%= @category.name %>
  </p>
<% end %>

lib/tq2_web/live/components/store/header_component.html.leex
<nav id="store-header-<%= @id %>" class="<%= nav_classes(@socket) %>" <%= maybe_shrink_hook(@socket) %>>
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <div class="mr-3 hide-on-shrink">
        <%= image @socket, @store %>
      </div>

      <div class="d-flex flex-grow-1">
        <div class="text-truncate flex-grow-1">
          <div class="mt-2 show-on-shrink"></div>
          <h1 class="h5 font-weight-bold text-truncate mb-1">
            <%= live_redirect to: Routes.counter_path(@socket, :index, @store), class: "text-reset text-decoration-none" do %>
              <%= @store.name %>
            <% end %>
          </h1>

          <div class="hide-on-shrink">
            <%= live_component @socket, InformationComponent, store: @store, class: "h4" %>
          </div>
        </div>

        <div class="show-on-shrink">
          <div class="row row-cols-2">
            <div class="col text-nowrap">
              <%= live_component @socket, InformationComponent, store: @store, class: "h4 mb-0 mt-n1 mt-lg-n2" %>
            </div>
            <div class="col text-right">
              <%= live_component @socket, ShareComponent, id: :header_shrink,
                                                          store: @store,
                                                          token: @token,
                                                          class: share_classes(),
                                                          align_right: true do %>
                <i class="bi-share-fill"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="float-right mt-n4 hide-on-shrink">
      <%= live_component @socket, ShareComponent, id: :header,
                                                  store: @store,
                                                  token: @token,
                                                  class: "#{share_classes()} mt-n3",
                                                  align_right: true do %>
        <i class="bi-share-fill"></i>
      <% end %>
    </div>

    <%= live_component @socket, TeamComponent, id: :team, store: @store, referral_customer: @referral_customer %>
  </div>

  <%= if Map.has_key?(assigns, :show_categories) do %>
    <nav class="navbar navbar-light row bg-white mt-3 mb-n2 py-0 px-4">
      <div class="col-6">
        <%= search_input(assigns) %>
      </div>
      <div class="col-6 col-md-auto text-truncate">
        <a href="#" class="float-right text-info" id="toggle-categories" phx-click="toggle-categories" phx-hook="ScrollToTop">
          <span class="mr-2 text-truncate">
            <%= categories_title(assigns) %>
          </span>

          <%= chevron_direction(@show_categories) %>
        </a>
      </div>
    </nav>
  <% end %>

  <%= if assigns[:show_teiqui_price_info] do %>
    <nav class="navbar navbar-light bg-primary text-white py-1 mb-1 mt-2"
         phx-hook="UpdateSession"
         id="teiqui-price-info"
         data-url="<%= Routes.store_dismiss_price_info_path(@socket, :dismiss_price_info, @store) %>">
      <div class="align-self-center mr-2 mt-1">
        <%= teiqui_logo_img_tag(@socket) %>
      </div>
      <div class="align-self-center flex-fill mt-1 font-weight-bolder">
        <%= dgettext("stores", "Teiqui price") %>
      </div>
      <div class="align-self-center mt-1">
        <%= link to: "#",
                 class: "h3 text-reset font-weight-bold",
                 phx_click: "dismiss",
                 phx_value_id: "price-info",
                 phx_target: @myself do %>
          &times;
        <% end %>
      </div>
    </nav>

    <nav class="navbar navbar-light bg-white text-dark py-2 mb-n2">
      <div class="align-self-center mx-4 mt-1 mb-2">
        <%= dgettext("stores", "Enjoy the discount making other people buy in the store or by joining to other customer.") %>
      </div>
    </nav>
  <% end %>
</nav>

<div class="<%= bottom_padding_classes(@socket) %>"></div>
<div class="<%= extra_bottom_padding_classes(@socket) %>"></div>

<%= if Map.has_key?(assigns, :show_categories) do %>
  <div class="py-3"></div>
<% end %>
<%= if assigns[:show_teiqui_price_info] do %>
  <div class="py-5 py-md-5 mb-4 mb-md-0"></div>
<% end %>

lib/tq2_web/live/components/store/information_component.html.leex
<%= if @store.data && @store.data.facebook do %>
  <%= link to: "https://www.facebook.com/#{@store.data.facebook}",
           class: "#{@class} text-reset text-decoration-none mr-2 mb-0",
           title: @store.data.facebook,
           target: "_blank" do %>
    <i class="bi-facebook"></i>
  <% end %>
<% end %>

<%= if @store.data && @store.data.instagram do %>
  <%= link to: "https://www.instagram.com/#{@store.data.instagram}",
           class: "#{@class} text-reset text-decoration-none mr-2 mb-0",
           title: @store.data.instagram,
           target: "_blank" do %>
    <i class="bi-instagram"></i>
  <% end %>
<% end %>

<%= if @store.data && @store.data.whatsapp do %>
  <%= link to: "https://wa.me/#{@store.data.whatsapp}",
           class: "#{@class} text-reset text-decoration-none mr-2 mb-0",
           title: @store.data.whatsapp,
           target: "_blank" do %>
    <i class="bi-whatsapp"></i>
  <% end %>
<% end %>

lib/tq2_web/live/components/store/item_component.html.leex
<%= live_redirect to: path(@socket, @store, @item, assigns[:search_params]), class: "col text-decoration-none", id: "item-#{@item.id}" do %>
  <div class="card mx-2 my-3 position-relative">
    <div class="embed-responsive embed-responsive-1by1">
      <%= image @item %>
    </div>

    <div class="card-body py-3 px-2">
      <p class="card-text h6 text-truncate text-dark font-weight-semi-bold mb-1">
        <%= @item.name %>
      </p>

      <p class="card-text text-truncate text-muted small mb-1">
        <%= @item.description || {:safe, "&nbsp;"} %>
      </p>

      <%= price @cart, @item %>
      <%= promotional_price @socket, @cart, @item %>
    </div>
  </div>
<% end %>

lib/tq2_web/live/components/store/notification_component.html.leex
<div id="notification-subscription"
     phx-hook="Notification"
     phx-target="<%= @myself %>"
		 data-skip-subscription="<%= inspect @skip_subscription %>"
     data-server-key="<%= vapid_server_key() %>">
  <%= if @ask_for_notifications do %>
    <div class="card card-body border border-warning <%= assigns[:extra_card_class] %>">
      <div class="d-flex">
        <div class="lead mr-3">
          🔔
        </div>

        <div class="mx-0">
          <%= render_block @inner_block %>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col">
          <%= link dgettext("notifications", "Not for now"), to: "#",
                                                            class: "text-muted",
                                                            phx_click: "dismiss",
                                                            phx_target: @myself %>
        </div>

        <div class="col text-right">
          <%= link dgettext("notifications", "Yes"), to: "#", phx_click: "subscribe", phx_target: @myself %>
        </div>
      </div>
    </div>
  <% end %>
</div>

lib/tq2_web/live/components/store/options_component.html.leex
<div class="dropup">
  <button type="button"
          id="store-options"
          class="btn btn-primary btn-lg"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
    <i class="bi-three-dots-vertical"></i>
  </button>

  <div class="dropdown-menu text-center" aria-labelledby="store-options">
    <%= live_redirect dgettext("stores", "Checkout"), to: Routes.checkout_path(@socket, :index, @store),
                                                      class: "dropdown-item" %>
  </div>
</div>